### PR TITLE
Make flash attention compile on Windows.

### LINKED ISSUE #50: Fails to build on Windows
Flash-Attention currently fails to build on windows. There are 2 blockers:
1 - The STD needs to be set to c++17 by default, or it will fail due to static_assert `/gmem_tile.h(253): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)`
2 - MSVC quirks with std::conditional
`C:\flash-attention\csrc\flash_attn\src\fmha_fprop_fp16_kernel.sm80.cu(86): error C2975: '_Test': invalid template argument for 'std::conditional', expected compile-time constant expression`

With these two fixed, it compiles.

I "fixed" issue 2 by removing std::conditional and setting to __half, but of course that's not an actual solution - and I've no idea what is.

### PR DESCRIPTION
**Pull request by bob80333**
This should resolve #50.

I was able to compile with CUDA 11.6, PyTorch 12.1 + CUDA 11.6, and an RTX 3090 as the target.

I haven't run any checks to see if the results are correct, is there any scripts for this purpose?

I was able to run the benchmark and saw big improvements in speed (~1/5 the time for forward + backward)
Screenshot 2022-10-03 134837

Hopefully someone else can also try to compile with this fork and see if it works for them.  Maybe @C43H66N12O12S2 would be interested in trying?

Also, huge thanks to @C43H66N12O12S2 to narrowing down the cause to "MSVC quirks with std::conditional" and C++17 being needed for the compiler, with that I was able to find the issue.

### CODE REVIEW

**Comment by bob80333** [comment]
I saw the pytest part of the README and ran the tests.

790 tests, failed, 618 tests passed.  

However, some tests failed due to CUDA OOM errors, and some tests failed due to is_sm80 errors (`Expected is_sm80 to be true, but got false.`)

Only counting the tests that failed due to AssertionErrors (numeric errors), there are 355 tests that fail.  

The full list of failed tests is here:
[flash_attention_tests.txt](https://github.com/HazyResearch/flash-attention/files/9700974/flash_attention_tests.txt)

**Comment by yocabon** [comment]
Hi, quick comment in passing
```
        if (COND) {                                                                  \
            using elem_type = std::conditional<true, __nv_bfloat16, __half>::type;   \
            return __VA_ARGS__();                                                    \
        } else {                                                                     \
            using elem_type = std::conditional<true, __nv_bfloat16, __half>::type;   \
            return __VA_ARGS__();                                                    \
        }    
```

doesn't look right. Shouldn't one of the branch be false ?
and at this point, is the std::conditional useful at all ?, why not just:

```
        if (COND) {                                                                  \
            using elem_type = __nv_bfloat16;   \
            return __VA_ARGS__();                                                    \
        } else {                                                                     \
            using elem_type = __half;   \
            return __VA_ARGS__();                                                    \
        }                                                                            \
```

**Comment by Thomas-MMJ** [comment]
Compiles here.  For the tests I changed

` is_sm75 = torch.cuda.get_device_capability('cuda') == (7, 5)

to

` is_sm75 = torch.cuda.get_device_capability('cuda') >= (7, 5)

since it was using that to check if it could do float16, such as

`@pytest.mark.parametrize('dtype', ([torch.float16] if is_sm75 else [torch.float16, torch.bfloat16]))

with that here are the test results,

=========== 480 failed, 160 passed, 64 skipped in 130.28s (0:02:10) ===========

```
test_flash_attn.py  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [  7%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFssssssssFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 17%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssssssssFFFFFFFFFFFFFFFFFFFFF [ 27%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssssssssFFFFF [ 38%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 48%]
FFFssssssssFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 58%]
FFFFFFFFFFFFFFFFFFFssssssssFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 68%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssssssss............................. [ 79%]
...................................................ssssssss............. [ 89%]
```
...................................................................sssss [ 99%]
sss                                                                      [100%]

**Comment by tridao** [comment]
SM75 (Turing) only supports fp16, and SM80 and above (Ampere) supports both fp16 and bf16.
So if we're on SM75, we only run tests for fp16. If we're on SM80 and above, we run tests for both fp16 and bf16.

**Comment by Thomas-MMJ** [comment]
updated with results for both.

**Comment by tridao** [comment]
Thanks, I've just changed the tests to not run backward for headdim=128 unless it's on A100. Hopefully that would reduce the number of false positives.
Can you try again?

**Comment by bob80333** [comment]
> Hi, quick comment in passing
> 
> ```
>         if (COND) {                                                                  \
>             using elem_type = std::conditional<true, __nv_bfloat16, __half>::type;   \
>             return __VA_ARGS__();                                                    \
>         } else {                                                                     \
>             using elem_type = std::conditional<true, __nv_bfloat16, __half>::type;   \
>             return __VA_ARGS__();                                                    \
>         }    
> ```
> 
> doesn't look right. Shouldn't one of the branch be false ? and at this point, is the std::conditional useful at all ?, why not just:
> 
> ```
>         if (COND) {                                                                  \
>             using elem_type = __nv_bfloat16;   \
>             return __VA_ARGS__();                                                    \
>         } else {                                                                     \
>             using elem_type = __half;   \
>             return __VA_ARGS__();                                                    \
>         }                                                                            \
> ```

Thanks for catching that, looks like I committed the wrong version of the code, this may also explain some of the failed tests!

**Comment by bob80333** [comment]
Re-ran tests one more time with the latest change, they all passed.

1408 passed in 161.90s (0:02:41)

[flash_attn_test_v3.txt](https://github.com/HazyResearch/flash-attention/files/9711949/flash_attn_test_v3.txt)

**Comment by Thomas-MMJ** [comment]
updated results 3060 GPU w 6 GB vram

========== 199 failed, 1081 passed, 128 skipped in 94.33s (0:01:34) ===========

```
tests\test_flash_attn.py ............................................... [  3%]
........................................................................ [  8%]
.........FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssssssssssssssss............... [ 13%]
.................................FFF.................................... [ 18%]
.........................................FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 23%]
Fssssssssssssssss................FFF.................................... [ 28%]
........................................................................ [ 34%]
.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssssssssssssssss....................... [ 39%]
........................................................................ [ 44%]
.................................FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFsssssss [ 49%]
sssssssss............................................................... [ 54%]
.................................................................FFFFFFF [ 59%]
FFFFFFFFFFFFFFFFFFFFFFFFFssssssssssssssss............................... [ 64%]
........................................................................ [ 69%]
.........................FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFsssssssssssssss [ 74%]
sF...................................................................... [ 80%]
........................................................................ [ 85%]
.................ssssssssssssssss....................................... [ 90%]
........................................................................ [ 95%]
.................................................ssssssssssssssss        [100%]
```

[('test_flash_attn_unpadded_qkvpacked', 67),
 ('test_flash_attn_unpadded_kvpacked', 67),
 ('test_flash_attn_unpadded', 64),
 ('test_flash_attn_race_condition', 1)]

**Comment by Thomas-MMJ** [comment]
Just OOMs due to my 6GB card, everything else passes. 

[test_2_OOMs.txt](https://github.com/HazyResearch/flash-attention/files/9712609/test_2_OOMs.txt)

**Comment by tridao** [comment]
Thanks for your help with Windows compilation @bob80333 @Thomas-MMJ @yocabon.
